### PR TITLE
spring bootify

### PR DESCRIPTION
**Pull request by ullrichp**

### CODE REVIEW

**Comment by ullrichp** [comment]
@peterpunch - Das sollte es jetzt sein.

Zwei Probleme bleiben:
* Maven will das leere db/common Verzeichnis nicht erstellen
* und die .gitignore Dateien darin fehlen leider auch

Kannst du bei Gelegenheit mal gucken bitte?

Getestet habe ich mit `mvn install`aus diesem Branch heraus und dann `mvn archetype:generate -DarchetypeGroupId=com.rebuy.archetypes -DarchetypeArtifactId=rebuy-silo-archetype -DarchetypeVersion=2.0.3-SNAPSHOT -DgroupId=com.rebuy.service -DartifactId=desk-silo -Dpackage=com.rebuy.service.desk -Dversion=0.8.15-SNAPSHOT -DarchetypeRepository=local` aus dem Verzeichnis über dem gewünschten Projektverzeichis.

**Comment by peterpunch** [comment]
Ja, leere Verzeichnisse gehen nicht. Konnte nie herausfinden, wie man das macht.
Man kann eine Dummy-Datei anlegen und die in die Includes mit aufnehmen. Am besten eine leere default.sql Datei, oder so.

**Comment by peterpunch** [comment]
:+1:

**Comment by ullrichp** [comment]
@rebuy-de/it-development - i like to know your opinion and thoughts, si vous plait ...maybe someone even creates a new project and checks if everything is working as expected (i have done this over and over ...)

File: src/main/resources/archetype-resources/silo/pom.xml [hunk 1]
```diff
@@ -154,26 +103,55 @@
             <version>${rebuy.messaging.version}</version>
             <exclusions>
                 <exclusion>
-                    <groupId>org.springframework</groupId>
-                    <artifactId>spring-context</artifactId>
+                    <artifactId>spring-integration-amqp</artifactId>
```
Comment (bjoernhaeuser) [inline src/main/resources/archetype-resources/silo/pom.xml]: Why?

File: src/main/resources/archetype-resources/silo/pom.xml [hunk 2]
```diff
@@ -249,4 +263,42 @@
...
+        <mockito.version>1.10.19</mockito.version>
+        <querydsl.version>3.6.7</querydsl.version>
+        <rebuy.common.version>3.2.0</rebuy.common.version>
+        <rebuy.customer-client.version>1.4.0</rebuy.customer-client.version>
+        <rebuy.messaging.version>3.0.1</rebuy.messaging.version>
+        <rebuy.projector.version>3.0.2</rebuy.projector.version>
+        <rebuy.security.version>2.0.0</rebuy.security.version>
+        <spring-integration-amqp.version>4.2.0.RELEASE</spring-integration-amqp.version>
+        <spring-integration-core.version>4.2.0.RELEASE</spring-integration-core.version>
+        <spring.boot.version>1.2.6.RELEASE</spring.boot.version>
```
Comment (bjoernhaeuser) [inline src/main/resources/archetype-resources/silo/pom.xml]: 1.3.0 is the current one :)

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java [hunk 3]
```diff
@@ -3,25 +3,13 @@
...
-import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
-import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
+import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
+import org.springframework.transaction.annotation.EnableTransactionManagement;
 
 import javax.sql.DataSource;
 
-@Configuration
-@Profile("!testing")
+@EnableTransactionManagement
```
Comment (bjoernhaeuser) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java]: That should not be necessary in a spring-boot-autoconfigure-world

File: src/main/resources/archetype-resources/silo/pom.xml (hunk 1 above)
Comment (ullrichp) [inline src/main/resources/archetype-resources/silo/pom.xml]: Because current messaging library includes 4.1.1.RELEASE

File: src/main/resources/archetype-resources/messages/pom.xml [hunk 4]
```diff
@@ -2,47 +2,39 @@
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
     <parent>
-        <groupId>${groupId}</groupId>
         <artifactId>${rootArtifactId}</artifactId>
+        <groupId>${groupId}</groupId>
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/messages/pom.xml]: Why did you move this line? I think it was better the way it was before.

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+import org.springframework.context.annotation.Bean;
+import org.springframework.context.annotation.Configuration;
+import org.springframework.context.annotation.Profile;
+
+@Configuration
+@Profile("!testing")
+public class ClientConfiguration
+{
+    @Bean
+    public CustomerClient customerClient(
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java]: Why is the customerClient configured by default?

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/LogConfiguration.java [hunk 6]
```diff
@@ -17,38 +16,28 @@
...
-public class LogConfiguration
-{
+public class LogConfiguration {
     @Autowired
-    Environment env;
+    private Environment env;
 
-    public void configureLog4j()
-    {
+    private void configureLog4j() throws IOException {
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/LogConfiguration.java]: codestyle: `{` in next line

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/LogConfiguration.java [hunk 7]
```diff
@@ -17,38 +16,28 @@
...
+            PropertyConfigurator.configure(properties);
         }
 
         BasicConfigurator.configure();
     }
 
     @Bean
-    public Logger logger(@Value("${logger.name}") String loggerName)
-    {
+    public Logger logger(@Value("${logger.name}") String loggerName) throws IOException {
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/LogConfiguration.java]: codestyle: `{` in next line

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java [hunk 8]
```diff
@@ -3,25 +3,12 @@
...
-import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
-import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
+import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
+import org.springframework.transaction.annotation.EnableTransactionManagement;
 
 import javax.sql.DataSource;
 
-@Configuration
-@Profile("!testing")
+@EnableJpaRepositories(basePackages = "${package}.${artifactId}")
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java]: You already have that annotated here: https://github.com/rebuy-de/rebuy-silo-archetype/pull/14/files#diff-3405101acf837027c5898c19b16037fcR19

I don't know if this configuration does anything after removing the annotation. So this class may become obsolete.

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/settings/DataSourceSettings.java [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+#set($symbol_dollar='$')
+#set($symbol_escape='\' )
+package ${package}.${artifactId}.configuration.settings;
+
+import org.springframework.boot.context.properties.ConfigurationProperties;
+import org.springframework.stereotype.Component;
+
+@Component
+@ConfigurationProperties("spring.datasource")
+public class DataSourceSettings
```
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/settings/DataSourceSettings.java]: I think this needs a `@Profile("!testing")`

File: src/main/resources/archetype-resources/messages/pom.xml (hunk 4 above)
Comment (ullrichp) [inline src/main/resources/archetype-resources/messages/pom.xml]: Blame the pomsorter from intellij. I just figured out that this plugin does some kind of custom sorting because the official https://maven.apache.org/developers/conventions/code.html (POM Code Convention) voted for an other sort order.

You can "test" or preview this kind of ordering with:
`mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort -Dsort.pomFile="src/main/resources/archetype-resources/silo/pom.xml" -Dsort.predefinedSortOrder="recommended_2008_06"` out of the root directory of this repository.

Let me know your thoughts.

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java (hunk 5 above)
Comment (ullrichp) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java]: I have one maybe common(?) example.

Comment (das-vinculum) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java]: I would let it there, if we have consul rolled out in all services, you will only need to initialize the client without any configuration. Then we can remove it.
A example always helps and most new silos should need that client.

Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java]: Okay fine for me.

File: src/main/resources/archetype-resources/messages/pom.xml (hunk 4 above)
Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/messages/pom.xml]: I like the ordering `recommended_2008_06` :+1:

**Comment by hendrik-rebuy** [comment]
the WebInitializer Configuration Class can also be removed for spring boot.

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java (hunk 8 above)
Comment (ullrichp) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java]: One Annotation is for "testing" and one for "!testing" ;)

Comment (JanZieglerBerlin) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java]: In that case its here already: https://github.com/rebuy-de/rebuy-silo-archetype/pull/14/files#diff-701d2d663d240275aa316f555f72b282R18

Comment (ullrichp) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/PersistenceConfiguration.java]: Now i see ... thanks.

**Comment by ullrichp** [comment]
@hendrik-rebuy - After upgrading the security lib to 4.0.0 there are some errors when build a silo from this branch:

`Error:(17, 13) java: cannot find symbol
  symbol:   class HeaderAuthorizationFilter
  location: class com.rebuy.service.awsome.silo.configuration.SpringSecurityConfig
`
or

`
Error:(29, 33) java: cannot find symbol
  symbol:   method headerAuthorizationFilter()
  location: class com.rebuy.service.awsome.silo.configuration.SecurityLibraryConfig
`

Is there any migration guide or something for version 4.0.0?

**Comment by hendrik-rebuy** [comment]
@ullrichp there is no guide but just do it like its in the payment-silo these configs are needed:
https://github.com/rebuy-de/payment-silo/blob/master/silo/src/main/java/com/rebuy/silo/payment/configuration/ResourceServerConfiguration.java
https://github.com/rebuy-de/payment-silo/blob/master/silo/src/main/java/com/rebuy/silo/payment/configuration/SpringSecurityConfiguration.java
the securityLibraryConfig can then be removed.

File: src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+
+        return customerClient;
+    }
+
+    private ClientConfig getClientConfig(CommonClientSettings commonClientSettings)
+    {
+        ClientConfig config = new ClientConfig();
+
+        config.property(ClientProperties.READ_TIMEOUT, commonClientSettings.readTimeout);
+        config.property(ClientProperties.CONNECT_TIMEOUT, commonClientSettings.connectTimeout);
```
Comment (sulimir) [inline src/main/resources/archetype-resources/silo/src/main/java/silo/configuration/ClientConfiguration.java]: +NL

File: src/main/resources/archetype-resources/silo/src/main/resources/db/common/V1__schema.sql [hunk 11]
```diff
@@ -0,0 +1,4 @@
+-- THIS IS AN EXAMPLE - THINK BEFORE YOU USE IT
```
Comment (sulimir) [inline src/main/resources/archetype-resources/silo/src/main/resources/db/common/V1__schema.sql]: Technically if there is V1 in common the min. index for migration/test is V2 imho.

File: src/main/resources/archetype-resources/silo/src/test/java/silo/demos/DemoIntegrationTest.java [hunk 12]
```diff
@@ -3,25 +3,17 @@
...
-import org.junit.runner.RunWith;
-import org.springframework.boot.test.SpringApplicationConfiguration;
-import org.springframework.boot.test.WebIntegrationTest;
-import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
+
 
 import static org.junit.Assert.*;
 
-@RunWith(SpringJUnit4ClassRunner.class)
 @Category(IntegrationTest.class)
```
Comment (sulimir) [inline src/main/resources/archetype-resources/silo/src/test/java/silo/demos/DemoIntegrationTest.java]: I think the @Category is inherited by BaseIntegrationTest.

File: src/main/resources/archetype-resources/silo/src/main/resources/db/common/V1__schema.sql (hunk 11 above)
Comment (ullrichp) [inline src/main/resources/archetype-resources/silo/src/main/resources/db/common/V1__schema.sql]: Because we dont know (if its possible) how to create empty folder with the archetype this is only a dummy file to have the folder common created.

Comment (sulimir) [inline src/main/resources/archetype-resources/silo/src/main/resources/db/common/V1__schema.sql]: I just thought that we could show people how the numbering would be done correctly in this exemple/dummy, but you have to know it anyway before you deploy anything so it's alright.

**Comment by peterpunch** [comment]
update

**Comment by bjoernhaeuser** [comment]
:+1:

**Comment by ullrichp** [comment]
Mir gefällts :+1:
